function compile_hdl_design_adaptive_filter
% compile_hdl_design_adaptive_filter compiles HDL design
% Generated by Cosimulation Wizard
[s, r] = system(['sh "hdlverifier_incisive_compile.sh"'],'-echo');
if (s ~= 0)
    error(message('HDLLink:CosimWizard:CompilationError',r));
end

