tclcmd = { ...
'exec xmelab  -64bit -access +wc  -File parameter_adaptive_filter.cfg adaptive_filter'
['hdlsimmatlabsysobj adaptive_filter  -64bit  -socket 36549', ...
' -input "{@simvision {set w \[waveform new\]}}"', ...
' -input "{@simvision {waveform add -using \$w -signals adaptive_filter}}"', ...
' -input "{@probe -create -shm adaptive_filter}"',... 
' -input "{@database -open waves -into waves.shm -default}"',... 
]};
nclaunch('tclstart',tclcmd);
